/** Stable marker for the accepted domain package boundary. */
export const packageBoundary = "@rsrender/domain" as const;

export {
  decodeDomainValueRecord,
  domainValueRecordsEqual,
  domainValueRecordVersion,
  encodeDomainValueRecord,
} from "./value-record.js";
export type {
  AssociationState,
  ContentState,
  DomainValueDecodeResult,
  DomainValueEncodeResult,
  DomainValueRecord,
  DomainValueRejectionCode,
  EligibilityReasonCode,
  EligibilityResult,
  FinalityState,
  ProvenanceTransformation,
  UnitState,
  ValueProvenance,
} from "./value-record.js";

export {
  aggregateSkeletonVersion,
  boringLogIdentityCodec,
  createEmptyLogProject,
  createEmptyLogTemplate,
  decodeLogProjectAggregate,
  decodeLogTemplateAggregate,
  deriveBoringLogIdentity,
  deriveEmbeddedTemplateRepresentationIdentity,
  deriveExplorationGroupIdentity,
  deriveExplorationMembershipIdentity,
  deriveLogSetIdentity,
  deriveTemplateAssignmentIdentity,
  divergeEmbeddedTemplateRepresentation,
  documentIdentityCodec,
  embeddedTemplateRepresentationIdentityCodec,
  encodeLogProjectAggregate,
  encodeLogTemplateAggregate,
  evaluateCompleteTemplateAssignments,
  explorationGroupIdentityCodec,
  explorationMembershipIdentityCodec,
  localAssignmentIdentityCodec,
  localGroupIdentityCodec,
  logSetIdentityCodec,
  replaceSharedEmbeddedTemplateRepresentation,
  resolveEffectiveTemplateAssignment,
  separationOperationIdentityCodec,
  sourceContextIdentityCodec,
  sourceExplorationIdentityCodec,
  sourceProjectIdentityCodec,
  templateAssignmentIdentityCodec,
  templateIdentityCodec,
} from "./aggregate-skeleton.js";

export {
  compareDiagnosticFacts,
  createDiagnosticFact,
  decodeDiagnosticFact,
  decodeDiagnosticFactSet,
  diagnosticFactContractRevision,
  diagnosticFactVersion,
  DIAGNOSTIC_FACT_CATEGORIES,
  DIAGNOSTIC_FACT_CONSEQUENCES,
  encodeDiagnosticFact,
  encodeDiagnosticFactSet,
} from "./diagnostic-fact.js";
export type {
  DiagnosticFact,
  DiagnosticFactAffectedIdentity,
  DiagnosticFactCategory,
  DiagnosticFactCause,
  DiagnosticFactComparisonResult,
  DiagnosticFactConsequence,
  DiagnosticFactDecodeResult,
  DiagnosticFactDraft,
  DiagnosticFactEncodeResult,
  DiagnosticFactInput,
  DiagnosticFactOrderingKey,
  DiagnosticFactRejectionCode,
  DiagnosticFactSetDecodeResult,
  DiagnosticFactSetEncodeResult,
} from "./diagnostic-fact.js";
export type {
  AggregateDecodeResult,
  AggregateEncodeResult,
  AggregateRejectionCode,
  BoringLogIdentity,
  CompleteAssignmentEvaluationResult,
  DocumentIdentity,
  EffectiveAssignmentResult,
  EffectiveTemplateAssignment,
  EmbeddedTemplateRepresentation,
  EmbeddedTemplateRepresentationIdentity,
  EmbeddedTemplateRepresentationOrigin,
  ExplorationGroup,
  ExplorationGroupIdentity,
  ExplorationMembership,
  ExplorationMembershipIdentity,
  LocalAssignmentIdentity,
  LocalGroupIdentity,
  LogProjectAggregate,
  LogSetComposition,
  LogSetIdentity,
  LogTemplateAggregate,
  SeparationOperationIdentity,
  SourceContextIdentity,
  SourceExplorationIdentity,
  SourceProjectIdentity,
  TemplateAssignment,
  TemplateAssignmentIdentity,
  TemplateAssignmentScope,
  TemplateIdentity,
} from "./aggregate-skeleton.js";

export {
  createSourceExtensionManifestEntry,
  createSourceExtensionObservation,
  createSourceFieldRecord,
  createSourceFieldTestColumn,
  createSourceLookupReference,
  createSourceRecord,
  createSourceSnapshot,
  decodeSourceExtensionManifestEntry,
  decodeSourceExtensionObservation,
  decodeSourceFieldRecord,
  decodeSourceFieldTestColumn,
  decodeSourceLookupReference,
  decodeSourceRecord,
  decodeSourceSnapshot,
  deriveSourceContextIdentity,
  deriveSourceEntityIdentity,
  deriveSourceExtensionManifestEntryIdentity,
  deriveSourceFieldIdentity,
  deriveSourceFieldTestColumnFieldPath,
  deriveSourceSnapshotIdentity,
  encodeSourceFieldRecord,
  encodeSourceExtensionManifestEntry,
  encodeSourceExtensionObservation,
  encodeSourceFieldTestColumn,
  encodeSourceLookupReference,
  encodeSourceRecord,
  encodeSourceSnapshot,
  FIELD_TEST_PARSER_STATES,
  OPEN_HOLE_GROUNDWATER_KINDS,
  OPEN_HOLE_GROUNDWATER_STATUSES,
  sourceCandidateIdentityCodec,
  sourceEntityIdentityCodec,
  sourceExtensionManifestEntryIdentityCodec,
  sourceExtensionManifestVersion,
  sourceExtensionObservationVersion,
  sourceFieldIdentityCodec,
  sourceFieldRecordVersion,
  sourceFieldTestColumnVersion,
  sourceLookupReferenceVersion,
  sourceRecordVersion,
  sourceSnapshotContractRevision,
  sourceSnapshotIdentityCodec,
  sourceSnapshotVersion,
  SOURCE_EVIDENCE_BLOCKED_CAPABILITY_IDS,
  SOURCE_ENTITY_KINDS,
  SOURCE_EXTENSION_MAX_CANONICAL_BYTES,
  SOURCE_EXTENSION_MAX_DEPTH,
  SOURCE_EXTENSION_MAX_NODES,
  SOURCE_MAPPED_FIELD_PATHS,
  SOURCE_RECORD_FAMILY_RULES,
} from "./source-snapshot.js";
export type {
  FieldTestParserState,
  OpenHoleGroundwaterKind,
  OpenHoleGroundwaterStatus,
  SourceCandidateIdentity,
  SourceCommentRecord,
  SourceEntityIdentity,
  SourceEntityKind,
  SourceEvidenceBlockedCapability,
  SourceEvidenceBlockedCapabilityId,
  SourceExplorationRecord,
  SourceExtensionContent,
  SourceExtensionDeclaration,
  SourceExtensionJsonKind,
  SourceExtensionManifestEntry,
  SourceExtensionManifestEntryDecodeResult,
  SourceExtensionManifestEntryDraft,
  SourceExtensionManifestEntryIdentity,
  SourceExtensionObservation,
  SourceExtensionObservationDecodeResult,
  SourceExtensionObservationDraft,
  SourceFieldIdentity,
  SourceFieldRecord,
  SourceFieldRecordDecodeResult,
  SourceFieldRecordDraft,
  SourceFieldRecordEncodeResult,
  SourceFieldTestColumn,
  SourceFieldTestColumnDecodeResult,
  SourceFieldTestColumnDraft,
  SourceFieldTestRecord,
  SourceIdentityDerivationResult,
  SourceLookupRecord,
  SourceLookupReference,
  SourceLookupReferenceDecodeResult,
  SourceOpenHoleGroundwaterRecord,
  SourceProjectRecord,
  SourceRecord,
  SourceRecordDecodeResult,
  SourceRecordDraft,
  SourceRecordEncodeResult,
  SourceRecordFamily,
  SourceSampleRecord,
  SourceSnapshot,
  SourceSnapshotDecodeResult,
  SourceSnapshotDraft,
  SourceSnapshotEncodeResult,
  SourceSnapshotExplorationIdentity,
  SourceSnapshotIdentity,
  SourceSnapshotProjectIdentity,
  SourceSnapshotRejectionCode,
  SourceSnapshotComponentEncodeResult,
  SourceStratumRecord,
} from "./source-snapshot.js";

export {
  createEmptyPhase1LogProject,
  createEmptyProjectInputRevisionHandle,
  createProjectInputRevisionHandle,
  decodePhase1LogProjectAggregate,
  deriveEmptyProjectInputContentDigest,
  deriveProjectInputRevisionIdentity,
  divergePhase1EmbeddedTemplateRepresentation,
  encodePhase1LogProjectAggregate,
  evaluatePhase1CompleteTemplateAssignments,
  inspectPhase1ProjectAvailability,
  getProjectInputRevisionHandle,
  migrateLogProjectAggregateV1ToPhase1V2,
  phase1LogProjectAggregateVersion,
  phase1ProjectInputContractRevision,
  PROJECT_INPUT_COLLECTION_KINDS,
  projectInputRevisionHandleVersion,
  projectInputRevisionIdentityCodec,
  replacePhase1SharedEmbeddedTemplateRepresentation,
  resolvePhase1EffectiveTemplateAssignment,
  toLogProjectAggregateV1CompatibilityView,
} from "./project-input-revisions.js";
export type {
  Phase1AcceptedSnapshotIdentity,
  Phase1CompleteAssignmentEvaluationResult,
  Phase1CompatibilityViewResult,
  Phase1EffectiveAssignmentResult,
  Phase1LogProjectAggregate,
  Phase1ProjectAvailability,
  Phase1ProjectAvailabilityResult,
  Phase1ProjectCoreOperationResult,
  Phase1ProjectCompatibilityFailure,
  Phase1ProjectDecodeResult,
  Phase1ProjectEncodeResult,
  Phase1ProjectInputs,
  Phase1ProjectMigrationResult,
  Phase1ProjectRejectionCode,
  ProjectInputCollectionKind,
  ProjectInputContentDigestResult,
  ProjectInputRevisionDerivationResult,
  ProjectInputRevisionHandle,
  ProjectInputRevisionHandleResult,
  ProjectInputRevisionIdentity,
  ProjectInputRevisionLookupResult,
} from "./project-input-revisions.js";
