/** Stable marker for the accepted domain package boundary. */
export const packageBoundary = "@rsrender/domain" as const;

export {
  decodeDomainValueRecord,
  domainValueRecordsEqual,
  domainValueRecordVersion,
  encodeDomainValueRecord,
} from "./value-record.js";
export type {
  AssociationState,
  ContentState,
  DomainValueDecodeResult,
  DomainValueEncodeResult,
  DomainValueRecord,
  DomainValueRejectionCode,
  EligibilityReasonCode,
  EligibilityResult,
  FinalityState,
  ProvenanceTransformation,
  UnitState,
  ValueProvenance,
} from "./value-record.js";

export {
  aggregateSkeletonVersion,
  boringLogIdentityCodec,
  createEmptyLogProject,
  createEmptyLogTemplate,
  decodeLogProjectAggregate,
  decodeLogTemplateAggregate,
  deriveBoringLogIdentity,
  deriveEmbeddedTemplateRepresentationIdentity,
  deriveExplorationGroupIdentity,
  deriveExplorationMembershipIdentity,
  deriveLogSetIdentity,
  deriveTemplateAssignmentIdentity,
  divergeEmbeddedTemplateRepresentation,
  documentIdentityCodec,
  embeddedTemplateRepresentationIdentityCodec,
  encodeLogProjectAggregate,
  encodeLogTemplateAggregate,
  evaluateCompleteTemplateAssignments,
  explorationGroupIdentityCodec,
  explorationMembershipIdentityCodec,
  localAssignmentIdentityCodec,
  localGroupIdentityCodec,
  logSetIdentityCodec,
  replaceSharedEmbeddedTemplateRepresentation,
  resolveEffectiveTemplateAssignment,
  separationOperationIdentityCodec,
  sourceContextIdentityCodec,
  sourceExplorationIdentityCodec,
  sourceProjectIdentityCodec,
  templateAssignmentIdentityCodec,
  templateIdentityCodec,
} from "./aggregate-skeleton.js";
export type {
  AggregateDecodeResult,
  AggregateEncodeResult,
  AggregateRejectionCode,
  BoringLogIdentity,
  CompleteAssignmentEvaluationResult,
  DocumentIdentity,
  EffectiveAssignmentResult,
  EffectiveTemplateAssignment,
  EmbeddedTemplateRepresentation,
  EmbeddedTemplateRepresentationIdentity,
  EmbeddedTemplateRepresentationOrigin,
  ExplorationGroup,
  ExplorationGroupIdentity,
  ExplorationMembership,
  ExplorationMembershipIdentity,
  LocalAssignmentIdentity,
  LocalGroupIdentity,
  LogProjectAggregate,
  LogSetComposition,
  LogSetIdentity,
  LogTemplateAggregate,
  SeparationOperationIdentity,
  SourceContextIdentity,
  SourceExplorationIdentity,
  SourceProjectIdentity,
  TemplateAssignment,
  TemplateAssignmentIdentity,
  TemplateAssignmentScope,
  TemplateIdentity,
} from "./aggregate-skeleton.js";
